---
title: "Lab 1 - Data visualization"
author: "Carli Olsen"
format: pdf
editor: visual
---

## Load Packages

```{r}
#| label: load-packages
#| message: false

library(tidyverse)
library(viridis)
```

## Exercise 1

This histogram has a right skew. There appears to be an outlier around 90,000 because it is very far away from the median and there is a low frequency.

```{r}
ggplot(midwest, aes(x=popdensity)) +
  geom_histogram(binwidth = 10000) +
  labs(title = "Population Density of Midwest Counties",x = "Population Density",y = "Frequency")
```

## Exercise 2

```{r}
ggplot(midwest, aes(x=percollege, y = percbelowpoverty)) +
  geom_point(aes(color = state)) +
  labs(title = "College Degree vs. Below Poverty",x = "People with College Degree(%)",y = "People Below Poverty(%)", color = "State") +
  scale_color_viridis_d()
```

## Exercise 3

(Type your answer to Exercise 3 here. Add code chunks as needed. Don't forget to label your code chunk. Do not use spaces in code chunk labels.)

## Exercise 4

## Exercise 5

## Exercise 6

## Exercise 7
